import { DeviceView } from "@/components/device-view/DeviceView";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Barcha Productlar",
  description: "Generated by create next app",
};

const Product = async () => {
  const response = await fetch(
    "http://3.76.183.255:3030/api/devices?page=1&limit=10",
    {
      cache: "force-cache",
    }
  );
  const data = await response.json();

  return (
    <div>
      <DeviceView data={data.data} />
    </div>
  );
};

export default Product;
